# This is a basic workflow to help you get started with Actions

name: Build ChipsMMO and deploy to server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install TypeScript
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g typescript
      
      - name: Install npm packages for ChipsMMO
        run: npm install
          
      - name: Compile ChipsMMO
        run: tsc
      
      - name: Copy ChipsMMO levels into dist
        run: cp ./CHIPS_MMO.dat ./dist/CHIPS_MMO.dat

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }} 
          known_hosts: 'NA' # Next action step will find the known hosts

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_IP }} >> ~/.ssh/known_hosts

      - name: Stop current running ChipsMMO services and ensure necessary packages are installed
        uses: fifsky/ssh-action@58b3c484be9c20cf118fd3b939a6d2cb3c769512
        with:
          command: |
            npm install -g forever
            forever stopall
            rm -rf /home/dist/
            mkdir -p /home/dist/
            sudo apt-get update -y
            sudo apt-get install -y rsync
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm
            cd /home/dist/
            npm install express
            npm install tslib
            npm install lz-string
            npm install aws-sdk
            npm install dotenv
            npm install jsonwebtoken
            npm install socket.io
            npm install os-utils

          host: ${{ secrets.SSH_HOST_IP }}
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }} 

      - name: Copy ChipsMMO into server through SSH
        uses: Burnett01/rsync-deployments@0dc935cdecc5f5e571865e60d2a6cdc673704823
        with:
          switches: -avz
          path: ./dist/
          remote_path: /home/dist/
          remote_host: ${{ secrets.SSH_HOST_IP }}
          remote_user: root
          remote_key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }} 

      - name: Start ChipsMMO with forever.js
        uses: fifsky/ssh-action@58b3c484be9c20cf118fd3b939a6d2cb3c769512
        with:
          command: |
            cd /home/dist/
            forever stopall
            forever start server/index.js
          host: ${{ secrets.SSH_HOST_IP }}
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
